<?php
declare(strict_types=1);

// BusinessDayCalculator SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

BusinessDayCalculatorUtility::setRegistrar(function (BusinessDayCalculatorUtility $u): void {
    $u->clean = [BusinessDayCalculatorClean::class, 'call'];
    $u->done = [BusinessDayCalculatorDone::class, 'call'];
    $u->make_error = [BusinessDayCalculatorMakeError::class, 'call'];
    $u->feature_add = [BusinessDayCalculatorFeatureAdd::class, 'call'];
    $u->feature_hook = [BusinessDayCalculatorFeatureHook::class, 'call'];
    $u->feature_init = [BusinessDayCalculatorFeatureInit::class, 'call'];
    $u->fetcher = [BusinessDayCalculatorFetcher::class, 'call'];
    $u->make_fetch_def = [BusinessDayCalculatorMakeFetchDef::class, 'call'];
    $u->make_context = [BusinessDayCalculatorMakeContext::class, 'call'];
    $u->make_options = [BusinessDayCalculatorMakeOptions::class, 'call'];
    $u->make_request = [BusinessDayCalculatorMakeRequest::class, 'call'];
    $u->make_response = [BusinessDayCalculatorMakeResponse::class, 'call'];
    $u->make_result = [BusinessDayCalculatorMakeResult::class, 'call'];
    $u->make_point = [BusinessDayCalculatorMakePoint::class, 'call'];
    $u->make_spec = [BusinessDayCalculatorMakeSpec::class, 'call'];
    $u->make_url = [BusinessDayCalculatorMakeUrl::class, 'call'];
    $u->param = [BusinessDayCalculatorParam::class, 'call'];
    $u->prepare_auth = [BusinessDayCalculatorPrepareAuth::class, 'call'];
    $u->prepare_body = [BusinessDayCalculatorPrepareBody::class, 'call'];
    $u->prepare_headers = [BusinessDayCalculatorPrepareHeaders::class, 'call'];
    $u->prepare_method = [BusinessDayCalculatorPrepareMethod::class, 'call'];
    $u->prepare_params = [BusinessDayCalculatorPrepareParams::class, 'call'];
    $u->prepare_path = [BusinessDayCalculatorPreparePath::class, 'call'];
    $u->prepare_query = [BusinessDayCalculatorPrepareQuery::class, 'call'];
    $u->graphql_body = [BusinessDayCalculatorGraphql::class, 'body'];
    $u->graphql_errors = [BusinessDayCalculatorGraphql::class, 'errors'];
    $u->result_basic = [BusinessDayCalculatorResultBasic::class, 'call'];
    $u->result_body = [BusinessDayCalculatorResultBody::class, 'call'];
    $u->result_headers = [BusinessDayCalculatorResultHeaders::class, 'call'];
    $u->transform_request = [BusinessDayCalculatorTransformRequest::class, 'call'];
    $u->transform_response = [BusinessDayCalculatorTransformResponse::class, 'call'];
});
